# application-prod.properties

# Server Config
server.port=8080

# Production Database (MUST use environment variables)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA & Hibernate (Validate only in Prod)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Flyway (Enabled in Prod)
spring.flyway.enabled=true

# Logging (Info level for prod)
logging.level.root=INFO
logging.level.com.example.demo=INFO
logging.level.org.hibernate.SQL=WARN
